server: 
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/mybank?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 34d3c25ce2692ecbdb09d440d42ce98e
            # client-secret: 제품 설정 -> 카카오 로그인 -> 보안 -> Client Secret
            redirect-uri: http://localhost:80/kakao-callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              #- 제품 설정 -> 카카오 로그인 -> 동의 항목
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
    
#  h2:
#    console:
#      enabled: true
#  output:
#    ansi:
#      enabled: always

mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
logging:
  level:
    org.mybatis: DEBUG